# Generated by Django 3.2.3 on 2021-06-18 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
