# Generated by Django 3.2.3 on 2021-05-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
