# Generated by Django 3.2.3 on 2021-05-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogposts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
