# Generated by Django 3.2.3 on 2021-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogposts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='slug',
            field=models.SlugField(default='hello-world'),
            preserve_default=False,
        ),
    ]
