# Generated by Django 3.2.3 on 2021-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogposts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
