# Generated by Django 3.2.3 on 2021-05-31 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogposts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogposts',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
