# Generated by Django 3.2.3 on 2021-06-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210607_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='car_makes',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='residence',
        ),
        migrations.DeleteModel(
            name='CarMake',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Residence',
        ),
    ]
