# Generated by Django 3.2.3 on 2021-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210608_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
