# Generated by Django 3.2.3 on 2021-06-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], max_length=6)),
            ],
            options={
                'ordering': ['complete', 'priority'],
            },
        ),
    ]
