# Generated by Django 3.2.3 on 2021-06-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 3), ('Medium', 2), ('Low', 1)], max_length=6),
        ),
    ]
